export * from "./Home";
export * from "./About";
export * from "./Contact";
export * from "./Project";
export * from "./Service";
export * from "./NewsPages";
export * from "./NewsDetailPages";
export * from "./PrivacyPolicy";
export * from "./TermsAndConditions";
